### ISSUE TITLE
NameError: Error fill report: Java package 'net' is not valid

### ISSUE THREAD

**Issue by predatorkind** [acesseonline/pyreportjasper#105]
I cannot fill a report generated in jasper studio. The below is the only error message I am getting.

\Anaconda3\lib\site-packages\pyreportjasper\pyreportjasper.py", line 182, in process_report
    raise error
NameError: Error fill report: Java package 'net' is not valid

**Comment by jadsonbr** [comment]
Remove the current installation and install via git to use a compiled version for your operating system.

```pip install git+https://github.com/acesseonline/pyreportjasper@master#egg=pyreportjasper```

**Comment by predatorkind** [comment]
I have created brand new environment installed pyreportjasper from git and  am still the same error.

**Comment by predatorkind** [comment]
Update. I tried unpacking all the jar files in libs folder one by one. Started with jasper reports.jar. with each file I would get a different error saying something else is missing. Somehow the script does not want to read .jar files for me. Any idea what might be causing this?

**Comment by jadsonbr** [comment]
@predatorkind You could give us more details by filling in the questionnaire so that we can investigate further.


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Python version [e.g. 3.8]
 - Library version [e.g. 2.1.0]
 - Java version [e.g. 15] 
 - JVM [e.g. Oracle]

**Jaspersoft Studio (please complete the following information):**
 - Version [e.g. 6.16.0]

**Additional context**
Add any other context about the problem here.

**Comment by jadsonbr** [comment]
Closed for lack of interaction
