### ISSUE TITLE
multilingual support

### ISSUE THREAD

**Issue by paymankooshkbaghi** [acesseonline/pyreportjasper#111]
Hi everyone
I want to use this function in another language. Is it multilingual function?
thanks

**Comment by paymankooshkbaghi** [comment]
Is it a mutilingual function?

**Comment by jadsonbr** [comment]
To use with another language, use the locale parameter.
[See an example here](https://pyreportjasper.readthedocs.io/en/latest/userguide.html#advanced-example-using-a-database)

For a complete list of locales see [Supported Locales](https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html)

**Comment by paymankooshkbaghi** [comment]
Thanks for your comment. I changed the locale ID but it doesn't work yet.

**Comment by paymankooshkbaghi** [comment]
Actually when the output file is 'xlsx' it works but I want pdf format output and it doesn't work.

**Comment by jadsonbr** [comment]
You could give us more details by filling in the questionnaire so that we can investigate further.

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. Linux]
Python version [e.g. 3.8]
Library version [e.g. 2.1.0]
Java version [e.g. 15]
JVM [e.g. Oracle]
Jaspersoft Studio (please complete the following information):

Version [e.g. 6.16.0]
Additional context
Add any other context about the problem here.

**Comment by jadsonbr** [comment]
@paymankooshkbaghi 
What is the data source? Please provide us with the above information so we can help.

**Comment by jadsonbr** [comment]
Issue closed for lack of interaction.
