### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by alisufyanbaig-dev** [acesseonline/pyreportjasper#115]
Hi Dear:

I tested same report on jasper server and jasper designer they are very fast. Why when I use this library in python it is very slow even slower than wkhtml and fpdf2

Thanks

**Comment by jadsonbr** [comment]
In order to help please provide more details.


**Describe**
A clear and concise description.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Python version [e.g. 3.8]
 - Library version [e.g. 2.1.0]
 - Java version [e.g. 15] 
 - JVM [e.g. Oracle]

**Jaspersoft Studio (please complete the following information):**
 - Version [e.g. 6.16.0]

**Additional context**
Add any other context about the problem here.

**Comment by jadsonbr** [comment]
We performed some tests and identified the following situation.
In JasperSoft Studio in default view it takes less than 40s and we can get the same result by setting in our library the output type with jrprint which is the default JasperSoft Studio format. To really know the runtime for a pdf export change the output type in JasperSoft Studio to pdf and rerun the preview you will get the pdf export time by JasperSoft Studio.

Below is a screenshot of where to change.
![Jaspersoft-studio-print](https://user-images.githubusercontent.com/10354607/139715498-8c65cf5a-594d-4a73-a54b-97368c125bc7.png)

I am also attaching to this answer a test file with a csv of 400,000 records:
[Download_teste_csv.zip](https://github.com/acesseonline/pyreportjasper/files/7455158/teste-csv.zip)


Hope this helps.

**Comment by alisufyanbaig-dev** [comment]
Thanks for such a prompt and great response. Thank u Thank u 👍 

I am having this issue now when running your file

NameError: Error fill report: Erro fill internal: net.sf.jasperreports.engine.JRException: Error loading expression class: noDB45i18n_1635791994668_653189.

**Comment by alisufyanbaig-dev** [comment]
Thanks I solved the above issue. Thanks for such a prompt and great response. Thank u Thank u 👍
