### ISSUE TITLE
error creating pdf file from jrxml on linux ec2 instance

### ISSUE THREAD

**Issue by gholakemohit** [acesseonline/pyreportjasper#82]
Traceback (most recent call last):
  File "jsonStatic.py", line 41, in <module>
    json_to_pdf()
  File "jsonStatic.py", line 36, in json_to_pdf
    pyreportjasper.process_report()
  File "/usr/local/lib/python3.7/site-packages/pyreportjasper/pyreportjasper.py", line 182, in process_report
    raise error
NameError: Error fill report: Erro fill internal: java.lang.InternalError: java.lang.reflect.InvocationTargetException

**Comment by jadsonbr** [comment]
@gholakemohit 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Python version [e.g. 3.8]
 - Library version [e.g. 2.1.0]
 - Java version [e.g. 15] 
 - JVM [e.g. Oracle]

**Jaspersoft Studio (please complete the following information):**
 - Version [e.g. 6.16.0]

**Additional context**
Add any other context about the problem here.

**Comment by gholakemohit** [comment]
I have added logo image in Jasper report and compiled and able to generate pdf on windows platform.

But I have copied jaspersoft workspace on Linux EC 2. And changed path for logo image according to EC2 files structure in jrxml. But it is taking previous path from Windows while creating pdf. 
Where is the path saved other than jrxml file.

**Comment by jadsonbr** [comment]
Follow example using image.

[https://repl.it/@JadsonRibeiro/danfe-pyreportjasper#main.py](https://repl.it/@JadsonRibeiro/danfe-pyreportjasper#main.py)

**Comment by gholakemohit** [comment]
thanks
